# Generated by Django 3.0.5 on 2020-08-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20200825_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
