# Generated by Django 3.0.5 on 2020-08-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0003_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('temp', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
            ],
        ),
    ]
